# Generated by Django 2.2.24 on 2022-06-22 14:44

from django.db import migrations


def fill_new_building_by_year(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Flat.objects.filter(construction_year__gte=2015).update(new_building=True) 

class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_auto_20220622_1122'),
    ]

    operations = [
        migrations.RunPython(fill_new_building_by_year)
    ]


