# Generated by Django 2.2.24 on 2022-06-22 14:54

from django.db import migrations


def fill_new_building_by_year(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Flat.objects.filter(construction_year__lt=2015).update(new_building=False) 


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_auto_20220622_1744'),
    ]

    operations = [
        migrations.RunPython(fill_new_building_by_year)
    ]