# Generated by Django 2.2.24 on 2022-06-24 18:59

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0018_auto_20220623_1542'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='complaint_flat',
            new_name='flat',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='owner_flats',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='owner_pure_phone',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='owners_phonenumber',
        ),
        migrations.AddField(
            model_name='owner',
            name='flats',
            field=models.ManyToManyField(related_name='owners', to='property.Flat', verbose_name='Квартиры в собственности'),
        ),
        migrations.AddField(
            model_name='owner',
            name='phonenumber',
            field=models.CharField(default=1, max_length=20, verbose_name='Номер владельца'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='owner',
            name='pure_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Нормализованный номер владельца'),
        ),
    ]
